register
TripMemories-PA/api pull request #1
Opened 2024-04-17 22:00 UTC by Pbonnamy

Register with email and password

2024-04-18 06:51 UTC, noeoxycode requested changes

2024-04-18 06:51 UTC, noeoxycode commented on app/validators/auth.ts
> +    password: vine.string().minLength(3).maxLength(64),
On doit faire un truc pro
Pour moi dans ce cadre avec les exigences des profs, une validation ''si faible'' n'est pas suffisante je pense 
Je pense à au moins 8 caractères, une majuscule et peut-être un caractère spécial ?

2024-04-18 21:39 UTC, Pbonnamy commented on app/validators/auth.ts
> +    password: vine.string().minLength(3).maxLength(64),
Ouais après là ct plus une v1 y'aura plus de champs après de toute facon mais c fix 👍

2024-04-19 11:02 UTC, noeoxycode approved these changes

2024-04-19 12:21 UTC, merged

2024-04-24 22:18 UTC, Pbonnamy commented
![](https://github.trello.services/images/mini-trello-icon.png) [Register](https://trello.com/c/AdeGSA4i/6-register)